### ISSUE TITLE
Error when creating new note

### ISSUE THREAD

**Issue by AtomicNess123** [felko/neuron-mode#19]
I get this error when trying to create new note (I have set the notes path to the one below)

`Command "neuron --zettelkasten-dir /Users/USER/Dropbox/notes new Untitled" exited with code 127: zsh:1: command not found: neuron`

Any help welcome, thanks.

**Comment by felko** [comment]
Did you install [neuron](http://github.com/srid/neuron)? I should clarify in the README that you need it to make neuron-mode work.

Otherwise it looks like the `neuron` command is not in your PATH, if you installed neuron with nix you should have something like `. /Users/USER/.nix-profile/etc/profile.d/nix.sh` in your .zshrc.
