### ISSUE TITLE
Neuron-Mode should be able to be automatically enabled

### ISSUE THREAD

**Issue by bulbousBullfrog** [felko/neuron-mode#49]
When working with neuron .md files, neuron-mode is by default not enabled, resulting in the need to call M-x neuron-mode, for each file worked on. Maybe this is configurable, though it isn't documented yet on the GitHub page. 
For example when calling neuron mode actions such as neuron-create-and-insert-zettel-link, or neuron-open-zettel, it should be possible for the newly opened buffer to already be in neuron-mode

If there is an elisp line that can enable this behavior without just enabling neuron-mode for all .md files, it should be documented as a configuration option.

**Comment by felko** [comment]
neuron-mode is automatically enabled for any markdown file that is located by a zettelkasten, which are identified by directories that have a file named `neuron.dhall` at the root. This wasn't clear for another user so I tried to clear this up in the README a couple days ago:

> All commands are executed in the active zettelkasten which is either detected by
traversing the directory hierarchy upwards until a `neuron.dhall` file is met
(see [neuron configuration](https://neuron.zettel.page/2011701.html)), or
otherwise it uses the zettelkasten that is specified by
`neuron-default-zettelkasten-directory` (a path). Although `neuron.dhall` files
are not mandatory to use neuron itself, this is what enables neuron-mode
automatically when opening a markdown file

Please tell me if further explanation is needed.

Edit: I notice some typos and ambiguous statements, I need to correct those

Edit 2: corrected

**Comment by bulbousBullfrog** [comment]
Thank you, I actually checked the readme again before taking a look at this issue, and then was able to understand that a neuron.dhall was needed. I set it up and it works. Then I went to open this issue and saw your update. Thank you it seems like the updated clarification helped.
